### ISSUE TITLE
Empty lua stack and the main lua stack contains only gcrash

### ISSUE THREAD

**Issue by Flapchik** [Thomasims/GCrash#4]
Hey. Thanks for developing this module. Unfortunately, I have problems. Please help me to solve them.
```
Seg fault occured.

Main Lua stack:
#0	lua/autorun/server/gcrach.lua:26 in anonymous function() <26-45>

Lua crash handler:

Frame #0, @lua/autorun/server/gcrach.lua:26:
  write = function: 0xdcc17760
```
and
```
Seg fault occured.

Main Lua stack:

Lua crash handler:


```

**Comment by Thomasims** [comment]
Hi, I'm investigating the reason why the first one shows up (I have another case where GCrash appears in the trace), so far I haven't found a reason to suspect GCrash is causing any issue itself.
The second is simply a segfault happening when no Lua is running. GCrash cannot help with these cases, I recommend just sending the coredump ('core' file) to Facepunch for proper analysis.

**Comment by GranDaddySmoke** [comment]
Seg fault occured.

Main Lua stack:
#0    lua/autorun/server/gcrash.lua:27 in anonymous function() <27-46>

Lua crash handler:
I have been getting this a lot.

**Comment by Thomasims** [comment]
I haven't found anything new since my last message, my best guess is that the Lua state gets corrupted to the point where calling a lua function on top of that stack just panics out again. This theory is shaky and probably not correct but there's nothing else I can do, if it's corrupted that bad I can't reliably inspect it.
